### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by igorageev** [temoncher/luscher-test#22]
Greetings!
Very interesting solution.

There is a typo in the example:
https://github.com/temoncher/luscher-test/blob/master/README.md#two-stage-test

1. In array `firstSelection` number 6 appears twice and number 5 is missing. 
2. The `await` operator (before calling the `getInterpretation` method) can only be used inside an async function or at the top level of a module.

**Comment by temoncher** [comment]
Hi, thank you for pointing this out

fixed in 9d519b2e1f9a610b8a5b583af1283307ae285f12
